# Generated by Django 3.2.8 on 2021-11-11 13:58

from django.db import migrations, models
import tips.models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='audio',
            field=models.FileField(upload_to='audios/', validators=[tips.models.validate_audio_extension]),
        ),
    ]
