# Generated by Django 3.2.8 on 2021-11-13 12:54

from django.db import migrations, models
import tips.models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_auto_20211112_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.FileField(max_length=1000, upload_to=tips.models.upload_audio, validators=[tips.models.validate_audio_extension]),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(max_length=1000, upload_to=tips.models.upload_image),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(max_length=1000, upload_to=tips.models.upload_video, validators=[tips.models.validate_video_extension]),
        ),
    ]
